-- Pre-computed year digests: one chronological synthesis per archive year,
-- injected into survey-question prompts as trusted NON-EVIDENCE guidance
-- (never citable; claims still require cited articles). Regenerated by
-- scripts/db/generate-year-digests.mjs.

CREATE TABLE IF NOT EXISTS year_digests (
  year          INTEGER PRIMARY KEY,
  digest        TEXT NOT NULL,
  article_count INTEGER NOT NULL,
  model         TEXT NOT NULL,
  generated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
