"""One-time cleanup: Fix AI-generated image captions and remove ghost articles.

Scans all edition.json files, sends AI-generated captions to Gemini Flash
to convert them to natural newspaper captions, removes ghost articles whose
bodies are pure AI image descriptions, and re-writes cleaned edition.json files.

Usage:
    python scripts/cleanup-ai-captions.py                    # dry run
    python scripts/cleanup-ai-captions.py --apply             # write changes
    python scripts/cleanup-ai-captions.py --apply --date 2000-09-13  # single edition
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
import time

# Add OCR source to path for Gemini client
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "ocr", "src"))

from google import genai

# ── AI caption detection ──────────────────────────────────────

AI_PATTERNS = re.compile(
    "|".join([
        r"^a (?:black and white |color |sepia |vintage )?(?:photo|photograph|picture|image|portrait|headshot)",
        r"^an (?:image|illustration|aerial|old)",
        r"^(?:portrait|headshot|photograph|photo) of ",
        r"^a (?:cartoon|comic|editorial cartoon|illustration|drawing|sketch|graphic)",
        r"^a (?:wide-angle|close-up|group) (?:photo|shot|image)",
        r"^a newspaper (?:clipping|page|article|photo)",
        r"^a (?:man|woman|person|student|group|team|crowd|building|scene) ",
        r"^the (?:photo|image|illustration|cartoon) (?:shows|depicts|features)",
        r"^(?:comic strip|editorial cartoon) ",
    ]),
    re.IGNORECASE,
)


def is_ai_caption(text: str) -> bool:
    """Check if a caption looks AI-generated."""
    text = text.strip()
    if not text:
        return False
    return bool(AI_PATTERNS.search(text[:200]))


def is_ghost_article(body: str) -> bool:
    """Check if an article body is a pure AI image description (ghost article)."""
    body = body.strip()
    if not body or len(body) > 300:
        return False
    if not is_ai_caption(body):
        return False
    # Real articles have multiple sentences; AI descriptions are usually one
    sentences = [s for s in re.split(r'[.!?]\s', body) if s.strip()]
    return len(sentences) <= 2


# ── Gemini cleanup ───────────────────────────────────────────

CLEANUP_PROMPT = """You are cleaning up image captions for a newspaper archive.
These captions were generated by an AI that described what it saw in photos/illustrations.
Convert each to a natural, concise newspaper caption.

Rules:
- If the description contains a quoted caption (e.g. captioned 'X'), extract X as the caption
- If it describes a person by name, use just their name (e.g. "A portrait of John Smith" → "John Smith")
- If it's a cartoon/illustration, use just the title if one exists, otherwise leave empty
- If it's a generic description with no useful info, return empty string ""
- Keep photographer credits if present (e.g. "Photo by Ed Jenkins")
- Never start with "A photo of" or "An image of" — that's the AI style we're removing
- Return ONLY the cleaned caption, nothing else

I'll send captions as a JSON array. Return a JSON array of the same length with cleaned captions.

Captions to clean:
"""

BATCH_SIZE = 30


def clean_captions_batch(client: genai.Client, captions: list[str]) -> list[str]:
    """Send a batch of AI captions to Gemini for cleanup."""
    prompt = CLEANUP_PROMPT + json.dumps(captions, indent=2)

    response = client.models.generate_content(
        model="gemini-3-flash-preview",
        contents=[prompt],
        config=genai.types.GenerateContentConfig(
            response_mime_type="application/json",
            max_output_tokens=8192,
        ),
    )

    try:
        result = json.loads(response.text)
        if isinstance(result, list) and len(result) == len(captions):
            return result
        print(f"  Warning: Gemini returned {len(result)} captions, expected {len(captions)}")
        return captions  # fallback: keep originals
    except (json.JSONDecodeError, TypeError):
        print(f"  Warning: Could not parse Gemini response, keeping originals")
        return captions


# ── Main ─────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Clean AI-generated captions from edition.json files")
    parser.add_argument("--apply", action="store_true", help="Write changes (default: dry run)")
    parser.add_argument("--date", type=str, help="Process single edition by date (YYYY-MM-DD)")
    args = parser.parse_args()

    # Load env
    env_path = os.path.join(ROOT, ".env.local")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                key, _, value = line.partition("=")
                value = value.strip("\"'")
                os.environ.setdefault(key, value)

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key and args.apply:
        print("ERROR: GOOGLE_API_KEY required for --apply mode")
        sys.exit(1)

    client = genai.Client(api_key=api_key) if api_key else None

    # Find editions
    editions_dir = os.path.join(ROOT, "public", "editions")
    if args.date:
        paths = [os.path.join(editions_dir, args.date, "edition.json")]
    else:
        paths = sorted(glob.glob(os.path.join(editions_dir, "*/edition.json")))

    total_captions_fixed = 0
    total_ghosts_removed = 0
    editions_modified = []

    # Collect all captions to clean across editions
    all_work: list[tuple[str, int, int, str]] = []  # (path, article_idx, image_idx, caption)
    ghost_work: list[tuple[str, int, str]] = []  # (path, article_idx, headline)

    for path in paths:
        if not os.path.exists(path):
            continue
        with open(path) as f:
            data = json.load(f)
        date = path.split(os.sep)[-2]

        for ai, art in enumerate(data.get("articles", [])):
            # Ghost articles
            body = (art.get("body") or "").strip()
            if is_ghost_article(body):
                ghost_work.append((path, ai, art.get("headline", "")))

            # AI captions
            for ii, img in enumerate(art.get("images", [])):
                cap = (img.get("caption") or "").strip()
                if is_ai_caption(cap):
                    all_work.append((path, ai, ii, cap))

    print(f"Found {len(all_work)} AI captions to clean across {len(paths)} editions")
    print(f"Found {len(ghost_work)} ghost articles to remove")
    print()

    if not args.apply:
        print("DRY RUN — no changes written. Use --apply to write changes.")
        print()
        print("Sample ghost articles:")
        for path, ai, headline in ghost_work[:10]:
            date = path.split(os.sep)[-2]
            print(f"  {date}: {headline}")
        print()
        print("Sample AI captions:")
        for path, ai, ii, cap in all_work[:10]:
            date = path.split(os.sep)[-2]
            print(f"  {date}: {cap[:100]}")
        return

    # ── Phase 1: Clean captions via Gemini ───────────────────
    print("Phase 1: Cleaning captions via Gemini...")
    captions_only = [w[3] for w in all_work]
    cleaned = []

    for i in range(0, len(captions_only), BATCH_SIZE):
        batch = captions_only[i : i + BATCH_SIZE]
        print(f"  Batch {i // BATCH_SIZE + 1}/{(len(captions_only) + BATCH_SIZE - 1) // BATCH_SIZE} ({len(batch)} captions)")
        result = clean_captions_batch(client, batch)
        cleaned.extend(result)
        time.sleep(0.5)

    # ── Phase 2: Apply changes to edition.json files ─────────
    print()
    print("Phase 2: Writing changes...")

    # Group changes by file
    changes_by_file: dict[str, dict] = {}

    # Caption changes
    for idx, (path, ai, ii, old_cap) in enumerate(all_work):
        new_cap = cleaned[idx] if idx < len(cleaned) else old_cap
        if new_cap != old_cap:
            changes_by_file.setdefault(path, {"captions": [], "ghost_indices": []})
            changes_by_file[path]["captions"].append((ai, ii, new_cap))

    # Ghost article removals
    for path, ai, headline in ghost_work:
        changes_by_file.setdefault(path, {"captions": [], "ghost_indices": []})
        changes_by_file[path]["ghost_indices"].append(ai)

    for path, changes in sorted(changes_by_file.items()):
        date = path.split(os.sep)[-2]
        with open(path) as f:
            data = json.load(f)

        # Apply caption changes
        for ai, ii, new_cap in changes["captions"]:
            if ai < len(data["articles"]) and ii < len(data["articles"][ai].get("images", [])):
                old = data["articles"][ai]["images"][ii]["caption"]
                data["articles"][ai]["images"][ii]["caption"] = new_cap
                total_captions_fixed += 1

        # Remove ghost articles (reverse order to preserve indices)
        for ai in sorted(changes["ghost_indices"], reverse=True):
            if ai < len(data["articles"]):
                headline = data["articles"][ai].get("headline", "")
                del data["articles"][ai]
                total_ghosts_removed += 1
                print(f"  {date}: removed ghost article '{headline}'")

        with open(path, "w") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

        editions_modified.append(date)

    print()
    print("=" * 60)
    print(f"Captions cleaned: {total_captions_fixed}")
    print(f"Ghost articles removed: {total_ghosts_removed}")
    print(f"Editions modified: {len(editions_modified)}")
    print()
    print("Next: re-seed affected editions:")
    print(f"  npm run db:seed")


if __name__ == "__main__":
    main()
